#
# Chef Server Config File
#
# Dynamically generated by Chef - local modifications will be replaced
#

log_level          :info
log_location       STDOUT
file_cache_path    "/tmp/chef"
cookbook_path      "/tmp/chef/cookbooks" 

Mixlib::Log::Formatter.show_time = false
